spring.application.name=zone

# Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.tustsiorwgvbrfmfcyjr
spring.datasource.password=prathmD@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable prepared statement caching
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect.postgresql.prepared_statement_cache=false
spring.jpa.properties.hibernate.query.plan_cache_enabled=false
spring.jpa.properties.hibernate.query.plan_parameter_metadata_max_size=0



# Optional: Disable OAuth2 startup requirement for Postman testing
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://tustsiorwgvbrfmfcyjr.supabase.co/auth/v1

